
// Question 1 (20%)
// Consider the F# type TwoLists and function f below.

type TwoLists = {listX: int list;
                 listY: int list}
let rec f {listX = lX; listY = lY} =
    match (lX, lY) with
    ([], [])-> f {listX=[]; listY=[]}           // Result is an infinity recursion. if both are empty then start empty lists. 
    | ([], y::ys)-> f {listX=[y]; listY = ys}   // put first element of Y into X and move it from Y
    | (x::xs, [])-> {listX=x::xs; listY = []}   // if Y is empty just keep X as is and keep Y empty
    | (xs, y::ys)-> f {listX=y::xs; listY = ys} // both lists contain something pu y in front of the X list

// Question 1.1
// • Explain what the type of function f is.

// ANSWER: The function takes a TwoLists and returns a TwoLists, where the elements from listY have been moved to listX.

// The function f has one input value for which it will initiate an unlimited number of recursive
// calls. Explain what input value that is and why it happens. Also, explain whether the function,
// with this input value will exhaust the stack or execute until manually interrupted.

// ANSWER:  The function enters and infinite recursive loop when both lists are empty. 
//          The function will eventually exhaust the stack and cause a stack overflow.

// Explain what the function f computes, when called with input values where f does terminate.
// Focus on what f does rather than how f does it.

// ANSWER: The function moves all elements from listY to the front of listX
//          and returns a new TwoLists value where listY is empty.


// Declare an F# function f2, similar to f, where the case with the unlimited number of recursive
// calls has been fixed. Show the result of evaluating f2 on the input value on which f does not
// terminate.

let rec f1 {listX = lX; listY = lY} =
    match (lX, lY) with
    ([], [])-> {listX=[]; listY=[]}           
    | ([], y::ys)-> f {listX=[y]; listY = ys}   
    | (x::xs, [])-> {listX=x::xs; listY = []}   
    | (xs, y::ys)-> f {listX=y::xs; listY = ys} 


// The function f can be simplified such that less than 4 cases in the pattern match are needed.
// Declare an F# function f3 with the outset in f or f2 with as few pattern match cases as possible.
// You must not use when guards.
let rec f2 {listX = lX; listY = lY} =
    match (lX, lY) with
    | (xs, []) -> {listX = xs; listY = []}      // if y is empty we stop recursion, we are done moving elements. 
    | (xs, y::ys)-> f {listX=y::xs; listY = ys} 


// Question 1.3
// Sequences are described in HR Chapter 11. Consider the F# declaration
let infSeq = Seq.initInfinite id

// Declare an infinite F# sequence mySeq of type seq<int*int> that generates the pair elements
// (i, −i) for all i ≥ 0. You may use infSeq to define mySeq.

let mySeq = Seq.map (fun i-> (i, -i)) infSeq
let mySeq2 = Seq.map (fun i-> (i, i*2)) infSeq

// Consider the expression below being the finite sequence of the first 1000 elements generated by
// mySeq. Each element is a pair (x,y).
// > Seq.take 1000 mySeq;;
// val it : seq<int * int> = seq [(0, 0); (1,-1); (2,-2); (3,-3); ...]
// Declare an F# expression of type bool that verifies the property that x + y = 0 for each pair in
// the sequence above:
// > <your code> (Seq.take 1000 mySeq);;
// val it : bool = true

let checkForZero sequence =
    Seq.forall (fun (x, y) ->  x + y = 0) sequence

checkForZero (Seq.take 1000 mySeq)

// Question 2 (25%)
// The concept of finite trees is described in HR Chapter 6. We define an album, Album, as a list of ele
// ments, Elem. Anelementcaneitherbeapictureelement, PicElemoranalbumelement, AlbumElem.

// The mutual recursive type below represents albums:
type Album = Elem list
and Elem = 
    PicElem of string
    | AlbumElem of string * Album


let header_familyPhoto = "Famliy Front Page"
let Family_Album : Elem list = []
let familySection : Elem = AlbumElem (header_familyPhoto, Family_Album)




let mainAlbum : Elem list = [PicElem "2001-2010";familySection; PicElem "2011-2020";  ]




// A picture element has a string representing the filename of the picture. An album element has a
// string representing the name of the album and the elements in the album represented by Album.
// Below F# declaration album1 corresponds to the album shown as a tree structure at right.
let pic1 = PicElem "Peter.jpg"
let pic2 = PicElem "Gitte.jpg"
let pic3 = PicElem "Mother.jpg"
let pic4 = PicElem "Farther.jpg"
let pic5 = PicElem "Hans.jpg"
let albumElem1 = AlbumElem ("Familiy", [pic3;pic4])
let albumElem2 = AlbumElem ("School", [pic5])
let albumElem3 = AlbumElem ("All", [pic1;albumElem1;pic2;albumElem2])
// let album1 = [albumElem3]

// Question 2.1
// • Answer yes or no to below questions and explain your answer:

// 1. Does the value pic1 have type Elem?               Yes, pic1 has type Elem.
// 2. Does the value albumElem1 have type Elem list?    No, it has type elm
// 3. Does the value album1 have type Elem list?        Yes, album1 has type Elem list.
// 4. Does the value album1 have type Album?            Yes, because Album is defined as Elem list.


// Declare an F# value album2 of type Album cor
// responding to the pictures and albums shown in the
// tree structure at right.
// • For each picture element, use the string <Name>.jpg, e.g., Per.jpg for Per and CoachAnna.jpg for Coach Anna.
let pic_kim = PicElem "kim.jpg"
let pic_per = PicElem "per.jpg"
let pic_ip = PicElem "ip.jpg"
let pic_anne = PicElem "anne.jpg"
let pic_CoachAnne = PicElem "CoachAnne.jpg"
let pic_CoachEmil = PicElem "CoachEmil.jpg"
let teamA_albumElem = AlbumElem ("TeamA", [pic_kim;pic_per])
let teamB_albumElem = AlbumElem ("TeamB", [pic_ip;pic_anne])
let basketTeam_albumElem = AlbumElem ("BasketTeam", [pic_CoachAnne;teamA_albumElem;pic_CoachEmil;teamB_albumElem])
let basketAlbum = [basketTeam_albumElem]

// • Are the types Album and Elem monomorphic or polymorphic? Explain your answer.
// they are monomorphic 


// Declare an F# function isAlbumElem elem of type Elem->bool that returns true if elem rep
// resents an album element; otherwise returns false. For instance isAlbumElem albumElem3
// returns true and isAlbumElem pic3 returns false.
// tag: match with a type type matching 

let isAlbumElem elem =
    match elem with
    | AlbumElem _ -> true
    | PicElem _ -> false



// Declare an F# function ppAlbum album of type Elem list-> string that returns a string
// representing a pretty printed album. The result string must have the format as shown below.

let newL i = System.Environment.NewLine + "".PadLeft(i,' ')

let rec ppAlbum album = 
    match album with 
    | [] -> "" 
    | h::t -> match h with 
                | PicElem name -> name + newL 0 + ppAlbum t // if its just a picture return it to name run ppAlbum on rest. 
                | AlbumElem (name, innerAlbum) -> name + newL 0 + ppAlbum innerAlbum + ppAlbum t 

ppAlbum basketAlbum

// Question 2.3
// • Declare an F# function countAlbum album of type Elem list-> int * int that returns
// a pair with first element being number of album elements and second element being number
// of picture elements. For instance countAlbum album1 evaluates to the pair (3,5). Also
// countAlbumalbum2evaluatesto(3,6). Notice, theimplementation of countAlbummust
// make use of the list library, e.g., a function like List.fold.

let rec countAlbum album = 
    List.fold (fun (albums, pictures) elem ->
        match elem with 
        | PicElem _ ->(albums, pictures + 1)
        | AlbumElem (_, innerAlbum) ->
            let (innerAlbums, innerPictures) = countAlbum innerAlbum
            (albums + 1 + innerAlbums, pictures + innerPictures)
    ) (0,0) album 
    // læg mærke til vi folder ALT ind i ( )

countAlbum basketAlbum

// TAG: FOLD EXAMPLE HELT SIMPELT 
let sumList numbers = 
    List.fold (fun sum element -> sum + element) 0 numbers


// Declare an F# function countAlbum2 with same type as countAlbum that returns exact same
// results as countAlbum. Only difference is that you must code your own helper function to
// traverse the list of picture and album elements, that is, no use of library aggregation functions like
// List.fold.

let rec countAlbum2 album =
    let rec helper elems (albums, pictures) =
        match elems with
        | [] -> (albums, pictures)

        | h::t ->
            match h with
            | PicElem _ ->
                helper t (albums, pictures + 1)

            | AlbumElem (_, innerAlbum) ->
                let (innerAlbums, innerPictures) = countAlbum2 innerAlbum

                helper t
                    (albums + 1 + innerAlbums,
                     pictures + innerPictures)

    helper album (0,0)



// Question 2.4
//  • Declare an F# function flattenAlbum album of type Elem list-> string list that
//  returns all album and picture element names in a list. You decide, but need to explain, what order
//  the names have in the result list. For instance, flattenAlbum album1 may return
//  val it : string list =
//  ["All"; "Peter.jpg"; "Familiy"; "Mother.jpg";
//  "Farther.jpg"; "Gitte.jpg"; "School"; "Hans.jpg"]


let rec flattenAlbum album = 
    match album with 
    | [] -> []
    | h::t -> match h with 
                | PicElem name -> [name] @ flattenAlbum t
                | AlbumElem (name, innerPictureLits) -> [name] @ flattenAlbum innerPictureLits @ flattenAlbum t

flattenAlbum basketAlbum

// Question 3 (30%)
// The concept of records and collections like lists and sets are described in HR Chapter 3 and 5. We define
// a multi stack as a stack that may contain two kinds of stack elements. Each kind has its own type. The
// type MultiStack below represents a multi stack